# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quotes

pod 'Firebase/Core'
pod 'Firebase/MLVision' 
pod 'Firebase/MLVisionTextModel'
pod 'Firebase/Analytics'
pod 'SnapKit', '~> 5.0.0'

end
