opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - convenience_type
  - empty_string
  - fatal_error_message
  - file_name
  - first_where
  - modifier_order
  - prohibited_interface_builder
  - toggle_bool
  - unused_private_declaration
excluded:
  - Pods
