# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'Quoteau' do
 inherit! :search_paths
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quoteau

  pod 'SnapKit', '~> 5.0'
  pod 'SwiftLint'

  # Pod for codable firebase
  pod 'CodableFirebase'
  
  # Pod for firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  # Pods for text recognition
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'

  # Pods for remote database
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  # Pod for remote storage
  pod 'Firebase/Storage'

  # Pod for local database
  pod 'RealmSwift'

  # Pods for Rxswift
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for Unit tests
   abstract_target 'Tests' do
    target "QuoteauTests"
    use_frameworks!

    pod 'Quick'
    pod 'Nimble'

  end
end
