# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'Quoteau' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quoteau

  pod 'SnapKit', '~> 5.0'
  pod 'SwiftLint'

  # Pod for firebase
  pod 'Firebase/Core'

  # Pods for text recognition
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'

  # Pods for remote database
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  # Pod for remote storage
  pod 'Firebase/Storage'

end
